pipeline {

    agent any

    tools {
        maven 'Maven'
        jdk 'JDK21'
    }

    stages {

        stage('Git Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/hariprasad2422/shopping-application.git'
            }
        }

        stage('Build Backend') {
            steps {
                dir('backend') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('Build Backend Image') {
            steps {
                dir('backend') {
                    sh 'docker build -t hariprasad2404/shopping-backend:v1 .'
                }
            }
        }

        stage('Build Frontend Image') {
            steps {
                dir('frontend') {
                    sh 'docker build -t hariprasad2404/shopping-frontend:v1 .'
                }
            }
        }

        stage('Push Backend Image') {
            steps {
                sh 'docker push hariprasad2404/shopping-backend:v1'
            }
        }

        stage('Push Frontend Image') {
            steps {
                sh 'docker push hariprasad2404/shopping-frontend:v1'
            }
        }

    }
}
